//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("Model", "DroitGroupe", "Droit", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VideoUploaderModel.Droit), "Groupe", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VideoUploaderModel.Groupe), true)]
[assembly: EdmRelationshipAttribute("Model", "GroupeUser", "Groupe", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VideoUploaderModel.Groupe), "User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VideoUploaderModel.User), true)]
[assembly: EdmRelationshipAttribute("Model", "UserFolder", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VideoUploaderModel.User), "Folder", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VideoUploaderModel.Element), true)]
[assembly: EdmRelationshipAttribute("Model", "ItemComment", "Item", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VideoUploaderModel.Item), "Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VideoUploaderModel.Comment), true)]
[assembly: EdmRelationshipAttribute("Model", "UserComment", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VideoUploaderModel.User), "Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VideoUploaderModel.Comment), true)]

#endregion

namespace VideoUploaderModel
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class ModelContext : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet ModelContext à l'aide de la chaîne de connexion trouvée dans la section 'ModelContext' du fichier de configuration d'application.
        /// </summary>
        public ModelContext() : base("name=ModelContext", "ModelContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet ModelContext.
        /// </summary>
        public ModelContext(string connectionString) : base(connectionString, "ModelContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet ModelContext.
        /// </summary>
        public ModelContext(EntityConnection connection) : base(connection, "ModelContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Droit> Droit
        {
            get
            {
                if ((_Droit == null))
                {
                    _Droit = base.CreateObjectSet<Droit>("Droit");
                }
                return _Droit;
            }
        }
        private ObjectSet<Droit> _Droit;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Groupe> Groupe
        {
            get
            {
                if ((_Groupe == null))
                {
                    _Groupe = base.CreateObjectSet<Groupe>("Groupe");
                }
                return _Groupe;
            }
        }
        private ObjectSet<Groupe> _Groupe;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<User> User
        {
            get
            {
                if ((_User == null))
                {
                    _User = base.CreateObjectSet<User>("User");
                }
                return _User;
            }
        }
        private ObjectSet<User> _User;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Element> Element
        {
            get
            {
                if ((_Element == null))
                {
                    _Element = base.CreateObjectSet<Element>("Element");
                }
                return _Element;
            }
        }
        private ObjectSet<Element> _Element;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<Comment> Comment
        {
            get
            {
                if ((_Comment == null))
                {
                    _Comment = base.CreateObjectSet<Comment>("Comment");
                }
                return _Comment;
            }
        }
        private ObjectSet<Comment> _Comment;

        #endregion
        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Droit. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToDroit(Droit droit)
        {
            base.AddObject("Droit", droit);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Groupe. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToGroupe(Groupe groupe)
        {
            base.AddObject("Groupe", groupe);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet User. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToUser(User user)
        {
            base.AddObject("User", user);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Element. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToElement(Element element)
        {
            base.AddObject("Element", element);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet Comment. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToComment(Comment comment)
        {
            base.AddObject("Comment", comment);
        }

        #endregion
    }
    

    #endregion
    
    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Comment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Comment : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Comment.
        /// </summary>
        /// <param name="idComment">Valeur initiale de la propriété IdComment.</param>
        /// <param name="contenu">Valeur initiale de la propriété Contenu.</param>
        /// <param name="dateCreation">Valeur initiale de la propriété DateCreation.</param>
        /// <param name="itemIdElement">Valeur initiale de la propriété ItemIdElement.</param>
        /// <param name="userIdUser">Valeur initiale de la propriété UserIdUser.</param>
        public static Comment CreateComment(global::System.Int64 idComment, global::System.String contenu, global::System.DateTime dateCreation, global::System.Int64 itemIdElement, global::System.Int32 userIdUser)
        {
            Comment comment = new Comment();
            comment.IdComment = idComment;
            comment.Contenu = contenu;
            comment.DateCreation = dateCreation;
            comment.ItemIdElement = itemIdElement;
            comment.UserIdUser = userIdUser;
            return comment;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 IdComment
        {
            get
            {
                return _IdComment;
            }
            set
            {
                if (_IdComment != value)
                {
                    OnIdCommentChanging(value);
                    ReportPropertyChanging("IdComment");
                    _IdComment = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdComment");
                    OnIdCommentChanged();
                }
            }
        }
        private global::System.Int64 _IdComment;
        partial void OnIdCommentChanging(global::System.Int64 value);
        partial void OnIdCommentChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Contenu
        {
            get
            {
                return _Contenu;
            }
            set
            {
                OnContenuChanging(value);
                ReportPropertyChanging("Contenu");
                _Contenu = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Contenu");
                OnContenuChanged();
            }
        }
        private global::System.String _Contenu;
        partial void OnContenuChanging(global::System.String value);
        partial void OnContenuChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreation
        {
            get
            {
                return _DateCreation;
            }
            set
            {
                OnDateCreationChanging(value);
                ReportPropertyChanging("DateCreation");
                _DateCreation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreation");
                OnDateCreationChanged();
            }
        }
        private global::System.DateTime _DateCreation;
        partial void OnDateCreationChanging(global::System.DateTime value);
        partial void OnDateCreationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ItemIdElement
        {
            get
            {
                return _ItemIdElement;
            }
            set
            {
                OnItemIdElementChanging(value);
                ReportPropertyChanging("ItemIdElement");
                _ItemIdElement = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ItemIdElement");
                OnItemIdElementChanged();
            }
        }
        private global::System.Int64 _ItemIdElement;
        partial void OnItemIdElementChanging(global::System.Int64 value);
        partial void OnItemIdElementChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserIdUser
        {
            get
            {
                return _UserIdUser;
            }
            set
            {
                OnUserIdUserChanging(value);
                ReportPropertyChanging("UserIdUser");
                _UserIdUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserIdUser");
                OnUserIdUserChanged();
            }
        }
        private global::System.Int32 _UserIdUser;
        partial void OnUserIdUserChanging(global::System.Int32 value);
        partial void OnUserIdUserChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "ItemComment", "Item")]
        public Item Item
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("Model.ItemComment", "Item").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("Model.ItemComment", "Item").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Item> ItemReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Item>("Model.ItemComment", "Item");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Item>("Model.ItemComment", "Item", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "UserComment", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserComment", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserComment", "User").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserComment", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("Model.UserComment", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Droit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Droit : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Droit.
        /// </summary>
        /// <param name="idDroit">Valeur initiale de la propriété IdDroit.</param>
        /// <param name="lirePublic">Valeur initiale de la propriété LirePublic.</param>
        /// <param name="ecrirePublic">Valeur initiale de la propriété EcrirePublic.</param>
        /// <param name="suppPublic">Valeur initiale de la propriété SuppPublic.</param>
        /// <param name="lirePrive">Valeur initiale de la propriété LirePrive.</param>
        /// <param name="ecrirePrive">Valeur initiale de la propriété EcrirePrive.</param>
        /// <param name="suppPrive">Valeur initiale de la propriété SuppPrive.</param>
        /// <param name="admin">Valeur initiale de la propriété Admin.</param>
        public static Droit CreateDroit(global::System.Int32 idDroit, global::System.Boolean lirePublic, global::System.Boolean ecrirePublic, global::System.Boolean suppPublic, global::System.Boolean lirePrive, global::System.Boolean ecrirePrive, global::System.Boolean suppPrive, global::System.Boolean admin)
        {
            Droit droit = new Droit();
            droit.IdDroit = idDroit;
            droit.LirePublic = lirePublic;
            droit.EcrirePublic = ecrirePublic;
            droit.SuppPublic = suppPublic;
            droit.LirePrive = lirePrive;
            droit.EcrirePrive = ecrirePrive;
            droit.SuppPrive = suppPrive;
            droit.Admin = admin;
            return droit;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdDroit
        {
            get
            {
                return _IdDroit;
            }
            set
            {
                if (_IdDroit != value)
                {
                    OnIdDroitChanging(value);
                    ReportPropertyChanging("IdDroit");
                    _IdDroit = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdDroit");
                    OnIdDroitChanged();
                }
            }
        }
        private global::System.Int32 _IdDroit;
        partial void OnIdDroitChanging(global::System.Int32 value);
        partial void OnIdDroitChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean LirePublic
        {
            get
            {
                return _LirePublic;
            }
            set
            {
                OnLirePublicChanging(value);
                ReportPropertyChanging("LirePublic");
                _LirePublic = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LirePublic");
                OnLirePublicChanged();
            }
        }
        private global::System.Boolean _LirePublic;
        partial void OnLirePublicChanging(global::System.Boolean value);
        partial void OnLirePublicChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean EcrirePublic
        {
            get
            {
                return _EcrirePublic;
            }
            set
            {
                OnEcrirePublicChanging(value);
                ReportPropertyChanging("EcrirePublic");
                _EcrirePublic = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EcrirePublic");
                OnEcrirePublicChanged();
            }
        }
        private global::System.Boolean _EcrirePublic;
        partial void OnEcrirePublicChanging(global::System.Boolean value);
        partial void OnEcrirePublicChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean SuppPublic
        {
            get
            {
                return _SuppPublic;
            }
            set
            {
                OnSuppPublicChanging(value);
                ReportPropertyChanging("SuppPublic");
                _SuppPublic = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SuppPublic");
                OnSuppPublicChanged();
            }
        }
        private global::System.Boolean _SuppPublic;
        partial void OnSuppPublicChanging(global::System.Boolean value);
        partial void OnSuppPublicChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean LirePrive
        {
            get
            {
                return _LirePrive;
            }
            set
            {
                OnLirePriveChanging(value);
                ReportPropertyChanging("LirePrive");
                _LirePrive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LirePrive");
                OnLirePriveChanged();
            }
        }
        private global::System.Boolean _LirePrive;
        partial void OnLirePriveChanging(global::System.Boolean value);
        partial void OnLirePriveChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean EcrirePrive
        {
            get
            {
                return _EcrirePrive;
            }
            set
            {
                OnEcrirePriveChanging(value);
                ReportPropertyChanging("EcrirePrive");
                _EcrirePrive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EcrirePrive");
                OnEcrirePriveChanged();
            }
        }
        private global::System.Boolean _EcrirePrive;
        partial void OnEcrirePriveChanging(global::System.Boolean value);
        partial void OnEcrirePriveChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean SuppPrive
        {
            get
            {
                return _SuppPrive;
            }
            set
            {
                OnSuppPriveChanging(value);
                ReportPropertyChanging("SuppPrive");
                _SuppPrive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SuppPrive");
                OnSuppPriveChanged();
            }
        }
        private global::System.Boolean _SuppPrive;
        partial void OnSuppPriveChanging(global::System.Boolean value);
        partial void OnSuppPriveChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Admin
        {
            get
            {
                return _Admin;
            }
            set
            {
                OnAdminChanging(value);
                ReportPropertyChanging("Admin");
                _Admin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Admin");
                OnAdminChanged();
            }
        }
        private global::System.Boolean _Admin;
        partial void OnAdminChanging(global::System.Boolean value);
        partial void OnAdminChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Element")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(Item))]
    [KnownTypeAttribute(typeof(Folder))]
    public partial class Element : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Element.
        /// </summary>
        /// <param name="idElement">Valeur initiale de la propriété IdElement.</param>
        /// <param name="nom">Valeur initiale de la propriété Nom.</param>
        /// <param name="dateCreation">Valeur initiale de la propriété DateCreation.</param>
        /// <param name="dateMAJ">Valeur initiale de la propriété DateMAJ.</param>
        /// <param name="userIdUser">Valeur initiale de la propriété UserIdUser.</param>
        public static Element CreateElement(global::System.Int64 idElement, global::System.String nom, global::System.DateTime dateCreation, global::System.DateTime dateMAJ, global::System.Int32 userIdUser)
        {
            Element element = new Element();
            element.IdElement = idElement;
            element.Nom = nom;
            element.DateCreation = dateCreation;
            element.DateMAJ = dateMAJ;
            element.UserIdUser = userIdUser;
            return element;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 IdElement
        {
            get
            {
                return _IdElement;
            }
            set
            {
                if (_IdElement != value)
                {
                    OnIdElementChanging(value);
                    ReportPropertyChanging("IdElement");
                    _IdElement = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdElement");
                    OnIdElementChanged();
                }
            }
        }
        private global::System.Int64 _IdElement;
        partial void OnIdElementChanging(global::System.Int64 value);
        partial void OnIdElementChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreation
        {
            get
            {
                return _DateCreation;
            }
            set
            {
                OnDateCreationChanging(value);
                ReportPropertyChanging("DateCreation");
                _DateCreation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreation");
                OnDateCreationChanged();
            }
        }
        private global::System.DateTime _DateCreation;
        partial void OnDateCreationChanging(global::System.DateTime value);
        partial void OnDateCreationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateMAJ
        {
            get
            {
                return _DateMAJ;
            }
            set
            {
                OnDateMAJChanging(value);
                ReportPropertyChanging("DateMAJ");
                _DateMAJ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateMAJ");
                OnDateMAJChanged();
            }
        }
        private global::System.DateTime _DateMAJ;
        partial void OnDateMAJChanging(global::System.DateTime value);
        partial void OnDateMAJChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserIdUser
        {
            get
            {
                return _UserIdUser;
            }
            set
            {
                OnUserIdUserChanging(value);
                ReportPropertyChanging("UserIdUser");
                _UserIdUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserIdUser");
                OnUserIdUserChanged();
            }
        }
        private global::System.Int32 _UserIdUser;
        partial void OnUserIdUserChanging(global::System.Int32 value);
        partial void OnUserIdUserChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "UserFolder", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserFolder", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserFolder", "User").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.UserFolder", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("Model.UserFolder", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Folder")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Folder : Element
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Folder.
        /// </summary>
        /// <param name="idElement">Valeur initiale de la propriété IdElement.</param>
        /// <param name="nom">Valeur initiale de la propriété Nom.</param>
        /// <param name="dateCreation">Valeur initiale de la propriété DateCreation.</param>
        /// <param name="dateMAJ">Valeur initiale de la propriété DateMAJ.</param>
        /// <param name="userIdUser">Valeur initiale de la propriété UserIdUser.</param>
        public static Folder CreateFolder(global::System.Int64 idElement, global::System.String nom, global::System.DateTime dateCreation, global::System.DateTime dateMAJ, global::System.Int32 userIdUser)
        {
            Folder folder = new Folder();
            folder.IdElement = idElement;
            folder.Nom = nom;
            folder.DateCreation = dateCreation;
            folder.DateMAJ = dateMAJ;
            folder.UserIdUser = userIdUser;
            return folder;
        }

        #endregion
    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Groupe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Groupe : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Groupe.
        /// </summary>
        /// <param name="idGroupe">Valeur initiale de la propriété IdGroupe.</param>
        /// <param name="nom">Valeur initiale de la propriété Nom.</param>
        /// <param name="dateCreation">Valeur initiale de la propriété DateCreation.</param>
        /// <param name="dateMAJ">Valeur initiale de la propriété DateMAJ.</param>
        /// <param name="droitIdDroit">Valeur initiale de la propriété DroitIdDroit.</param>
        public static Groupe CreateGroupe(global::System.Int32 idGroupe, global::System.String nom, global::System.DateTime dateCreation, global::System.DateTime dateMAJ, global::System.Int32 droitIdDroit)
        {
            Groupe groupe = new Groupe();
            groupe.IdGroupe = idGroupe;
            groupe.Nom = nom;
            groupe.DateCreation = dateCreation;
            groupe.DateMAJ = dateMAJ;
            groupe.DroitIdDroit = droitIdDroit;
            return groupe;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdGroupe
        {
            get
            {
                return _IdGroupe;
            }
            set
            {
                if (_IdGroupe != value)
                {
                    OnIdGroupeChanging(value);
                    ReportPropertyChanging("IdGroupe");
                    _IdGroupe = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdGroupe");
                    OnIdGroupeChanged();
                }
            }
        }
        private global::System.Int32 _IdGroupe;
        partial void OnIdGroupeChanging(global::System.Int32 value);
        partial void OnIdGroupeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descritpion
        {
            get
            {
                return _Descritpion;
            }
            set
            {
                OnDescritpionChanging(value);
                ReportPropertyChanging("Descritpion");
                _Descritpion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descritpion");
                OnDescritpionChanged();
            }
        }
        private global::System.String _Descritpion;
        partial void OnDescritpionChanging(global::System.String value);
        partial void OnDescritpionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreation
        {
            get
            {
                return _DateCreation;
            }
            set
            {
                OnDateCreationChanging(value);
                ReportPropertyChanging("DateCreation");
                _DateCreation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreation");
                OnDateCreationChanged();
            }
        }
        private global::System.DateTime _DateCreation;
        partial void OnDateCreationChanging(global::System.DateTime value);
        partial void OnDateCreationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateMAJ
        {
            get
            {
                return _DateMAJ;
            }
            set
            {
                OnDateMAJChanging(value);
                ReportPropertyChanging("DateMAJ");
                _DateMAJ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateMAJ");
                OnDateMAJChanged();
            }
        }
        private global::System.DateTime _DateMAJ;
        partial void OnDateMAJChanging(global::System.DateTime value);
        partial void OnDateMAJChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DroitIdDroit
        {
            get
            {
                return _DroitIdDroit;
            }
            set
            {
                OnDroitIdDroitChanging(value);
                ReportPropertyChanging("DroitIdDroit");
                _DroitIdDroit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DroitIdDroit");
                OnDroitIdDroitChanged();
            }
        }
        private global::System.Int32 _DroitIdDroit;
        partial void OnDroitIdDroitChanging(global::System.Int32 value);
        partial void OnDroitIdDroitChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "DroitGroupe", "Droit")]
        public Droit Droit
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Droit>("Model.DroitGroupe", "Droit").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Droit>("Model.DroitGroupe", "Droit").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Droit> DroitReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Droit>("Model.DroitGroupe", "Droit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Droit>("Model.DroitGroupe", "Droit", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Item")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Item : Element
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet Item.
        /// </summary>
        /// <param name="idElement">Valeur initiale de la propriété IdElement.</param>
        /// <param name="nom">Valeur initiale de la propriété Nom.</param>
        /// <param name="dateCreation">Valeur initiale de la propriété DateCreation.</param>
        /// <param name="dateMAJ">Valeur initiale de la propriété DateMAJ.</param>
        /// <param name="userIdUser">Valeur initiale de la propriété UserIdUser.</param>
        /// <param name="type">Valeur initiale de la propriété Type.</param>
        public static Item CreateItem(global::System.Int64 idElement, global::System.String nom, global::System.DateTime dateCreation, global::System.DateTime dateMAJ, global::System.Int32 userIdUser, global::System.String type)
        {
            Item item = new Item();
            item.IdElement = idElement;
            item.Nom = nom;
            item.DateCreation = dateCreation;
            item.DateMAJ = dateMAJ;
            item.UserIdUser = userIdUser;
            item.Type = type;
            return item;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descriptin
        {
            get
            {
                return _Descriptin;
            }
            set
            {
                OnDescriptinChanging(value);
                ReportPropertyChanging("Descriptin");
                _Descriptin = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descriptin");
                OnDescriptinChanged();
            }
        }
        private global::System.String _Descriptin;
        partial void OnDescriptinChanging(global::System.String value);
        partial void OnDescriptinChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Fichier
        {
            get
            {
                return StructuralObject.GetValidValue(_Fichier);
            }
            set
            {
                OnFichierChanging(value);
                ReportPropertyChanging("Fichier");
                _Fichier = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Fichier");
                OnFichierChanged();
            }
        }
        private global::System.Byte[] _Fichier;
        partial void OnFichierChanging(global::System.Byte[] value);
        partial void OnFichierChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UrlHD
        {
            get
            {
                return _UrlHD;
            }
            set
            {
                OnUrlHDChanging(value);
                ReportPropertyChanging("UrlHD");
                _UrlHD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UrlHD");
                OnUrlHDChanged();
            }
        }
        private global::System.String _UrlHD;
        partial void OnUrlHDChanging(global::System.String value);
        partial void OnUrlHDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UrlLD
        {
            get
            {
                return _UrlLD;
            }
            set
            {
                OnUrlLDChanging(value);
                ReportPropertyChanging("UrlLD");
                _UrlLD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UrlLD");
                OnUrlLDChanged();
            }
        }
        private global::System.String _UrlLD;
        partial void OnUrlLDChanging(global::System.String value);
        partial void OnUrlLDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet User.
        /// </summary>
        /// <param name="idUser">Valeur initiale de la propriété IdUser.</param>
        /// <param name="nom">Valeur initiale de la propriété Nom.</param>
        /// <param name="prenom">Valeur initiale de la propriété Prenom.</param>
        /// <param name="login">Valeur initiale de la propriété Login.</param>
        /// <param name="password">Valeur initiale de la propriété Password.</param>
        /// <param name="dateCreation">Valeur initiale de la propriété DateCreation.</param>
        /// <param name="dateMAJ">Valeur initiale de la propriété DateMAJ.</param>
        /// <param name="groupeIdGroupe">Valeur initiale de la propriété GroupeIdGroupe.</param>
        public static User CreateUser(global::System.Int32 idUser, global::System.String nom, global::System.String prenom, global::System.String login, global::System.String password, global::System.DateTime dateCreation, global::System.DateTime dateMAJ, global::System.Int32 groupeIdGroupe)
        {
            User user = new User();
            user.IdUser = idUser;
            user.Nom = nom;
            user.Prenom = prenom;
            user.Login = login;
            user.Password = password;
            user.DateCreation = dateCreation;
            user.DateMAJ = dateMAJ;
            user.GroupeIdGroupe = groupeIdGroupe;
            return user;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUser
        {
            get
            {
                return _IdUser;
            }
            set
            {
                if (_IdUser != value)
                {
                    OnIdUserChanging(value);
                    ReportPropertyChanging("IdUser");
                    _IdUser = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdUser");
                    OnIdUserChanged();
                }
            }
        }
        private global::System.Int32 _IdUser;
        partial void OnIdUserChanging(global::System.Int32 value);
        partial void OnIdUserChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Prenom
        {
            get
            {
                return _Prenom;
            }
            set
            {
                OnPrenomChanging(value);
                ReportPropertyChanging("Prenom");
                _Prenom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Prenom");
                OnPrenomChanged();
            }
        }
        private global::System.String _Prenom;
        partial void OnPrenomChanging(global::System.String value);
        partial void OnPrenomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreation
        {
            get
            {
                return _DateCreation;
            }
            set
            {
                OnDateCreationChanging(value);
                ReportPropertyChanging("DateCreation");
                _DateCreation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreation");
                OnDateCreationChanged();
            }
        }
        private global::System.DateTime _DateCreation;
        partial void OnDateCreationChanging(global::System.DateTime value);
        partial void OnDateCreationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateMAJ
        {
            get
            {
                return _DateMAJ;
            }
            set
            {
                OnDateMAJChanging(value);
                ReportPropertyChanging("DateMAJ");
                _DateMAJ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateMAJ");
                OnDateMAJChanged();
            }
        }
        private global::System.DateTime _DateMAJ;
        partial void OnDateMAJChanging(global::System.DateTime value);
        partial void OnDateMAJChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupeIdGroupe
        {
            get
            {
                return _GroupeIdGroupe;
            }
            set
            {
                OnGroupeIdGroupeChanging(value);
                ReportPropertyChanging("GroupeIdGroupe");
                _GroupeIdGroupe = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GroupeIdGroupe");
                OnGroupeIdGroupeChanged();
            }
        }
        private global::System.Int32 _GroupeIdGroupe;
        partial void OnGroupeIdGroupeChanging(global::System.Int32 value);
        partial void OnGroupeIdGroupeChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "GroupeUser", "Groupe")]
        public Groupe Groupe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Groupe>("Model.GroupeUser", "Groupe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Groupe>("Model.GroupeUser", "Groupe").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Groupe> GroupeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Groupe>("Model.GroupeUser", "Groupe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Groupe>("Model.GroupeUser", "Groupe", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
