//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("Model", "DroitGroupe", "Droit", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VideoUploaderModel.VUDroit), "Groupe", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VideoUploaderModel.VUGroupe), true)]
[assembly: EdmRelationshipAttribute("Model", "GroupeUser", "Groupe", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VideoUploaderModel.VUGroupe), "User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VideoUploaderModel.VUUser), true)]
[assembly: EdmRelationshipAttribute("Model", "UserFolder", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VideoUploaderModel.VUUser), "Folder", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VideoUploaderModel.VUElement), true)]
[assembly: EdmRelationshipAttribute("Model", "ItemComment", "Item", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VideoUploaderModel.VUItem), "Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VideoUploaderModel.VUComment), true)]
[assembly: EdmRelationshipAttribute("Model", "UserComment", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VideoUploaderModel.VUUser), "Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VideoUploaderModel.VUComment), true)]
[assembly: EdmRelationshipAttribute("Model", "VUFolderVUElement", "VUFolder", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(VideoUploaderModel.VUFolder), "VUElement", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VideoUploaderModel.VUElement), true)]
[assembly: EdmRelationshipAttribute("Model", "VUDroitElementVUElement", "VUDroitElement", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VideoUploaderModel.VUDroitElement), "VUElement", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VideoUploaderModel.VUElement), true)]

#endregion

namespace VideoUploaderModel
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class ModelContext : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet ModelContext à l'aide de la chaîne de connexion trouvée dans la section 'ModelContext' du fichier de configuration d'application.
        /// </summary>
        public ModelContext() : base("name=ModelContext", "ModelContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet ModelContext.
        /// </summary>
        public ModelContext(string connectionString) : base(connectionString, "ModelContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet ModelContext.
        /// </summary>
        public ModelContext(EntityConnection connection) : base(connection, "ModelContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<VUDroit> VUDroit
        {
            get
            {
                if ((_VUDroit == null))
                {
                    _VUDroit = base.CreateObjectSet<VUDroit>("VUDroit");
                }
                return _VUDroit;
            }
        }
        private ObjectSet<VUDroit> _VUDroit;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<VUGroupe> VUGroupe
        {
            get
            {
                if ((_VUGroupe == null))
                {
                    _VUGroupe = base.CreateObjectSet<VUGroupe>("VUGroupe");
                }
                return _VUGroupe;
            }
        }
        private ObjectSet<VUGroupe> _VUGroupe;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<VUUser> VUUser
        {
            get
            {
                if ((_VUUser == null))
                {
                    _VUUser = base.CreateObjectSet<VUUser>("VUUser");
                }
                return _VUUser;
            }
        }
        private ObjectSet<VUUser> _VUUser;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<VUElement> VUElement
        {
            get
            {
                if ((_VUElement == null))
                {
                    _VUElement = base.CreateObjectSet<VUElement>("VUElement");
                }
                return _VUElement;
            }
        }
        private ObjectSet<VUElement> _VUElement;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<VUComment> VUComment
        {
            get
            {
                if ((_VUComment == null))
                {
                    _VUComment = base.CreateObjectSet<VUComment>("VUComment");
                }
                return _VUComment;
            }
        }
        private ObjectSet<VUComment> _VUComment;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<VUDroitElement> VUDroitElement
        {
            get
            {
                if ((_VUDroitElement == null))
                {
                    _VUDroitElement = base.CreateObjectSet<VUDroitElement>("VUDroitElement");
                }
                return _VUDroitElement;
            }
        }
        private ObjectSet<VUDroitElement> _VUDroitElement;

        #endregion
        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet VUDroit. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToVUDroit(VUDroit vUDroit)
        {
            base.AddObject("VUDroit", vUDroit);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet VUGroupe. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToVUGroupe(VUGroupe vUGroupe)
        {
            base.AddObject("VUGroupe", vUGroupe);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet VUUser. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToVUUser(VUUser vUUser)
        {
            base.AddObject("VUUser", vUUser);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet VUElement. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToVUElement(VUElement vUElement)
        {
            base.AddObject("VUElement", vUElement);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet VUComment. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToVUComment(VUComment vUComment)
        {
            base.AddObject("VUComment", vUComment);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet VUDroitElement. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToVUDroitElement(VUDroitElement vUDroitElement)
        {
            base.AddObject("VUDroitElement", vUDroitElement);
        }

        #endregion
    }
    

    #endregion
    
    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="VUComment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VUComment : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet VUComment.
        /// </summary>
        /// <param name="idComment">Valeur initiale de la propriété IdComment.</param>
        /// <param name="contenu">Valeur initiale de la propriété Contenu.</param>
        /// <param name="dateCreation">Valeur initiale de la propriété DateCreation.</param>
        /// <param name="itemIdElement">Valeur initiale de la propriété ItemIdElement.</param>
        /// <param name="userIdUser">Valeur initiale de la propriété UserIdUser.</param>
        public static VUComment CreateVUComment(global::System.Int64 idComment, global::System.String contenu, global::System.DateTime dateCreation, global::System.Int64 itemIdElement, global::System.Int32 userIdUser)
        {
            VUComment vUComment = new VUComment();
            vUComment.IdComment = idComment;
            vUComment.Contenu = contenu;
            vUComment.DateCreation = dateCreation;
            vUComment.ItemIdElement = itemIdElement;
            vUComment.UserIdUser = userIdUser;
            return vUComment;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 IdComment
        {
            get
            {
                return _IdComment;
            }
            set
            {
                if (_IdComment != value)
                {
                    OnIdCommentChanging(value);
                    ReportPropertyChanging("IdComment");
                    _IdComment = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdComment");
                    OnIdCommentChanged();
                }
            }
        }
        private global::System.Int64 _IdComment;
        partial void OnIdCommentChanging(global::System.Int64 value);
        partial void OnIdCommentChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Contenu
        {
            get
            {
                return _Contenu;
            }
            set
            {
                OnContenuChanging(value);
                ReportPropertyChanging("Contenu");
                _Contenu = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Contenu");
                OnContenuChanged();
            }
        }
        private global::System.String _Contenu;
        partial void OnContenuChanging(global::System.String value);
        partial void OnContenuChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreation
        {
            get
            {
                return _DateCreation;
            }
            set
            {
                OnDateCreationChanging(value);
                ReportPropertyChanging("DateCreation");
                _DateCreation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreation");
                OnDateCreationChanged();
            }
        }
        private global::System.DateTime _DateCreation;
        partial void OnDateCreationChanging(global::System.DateTime value);
        partial void OnDateCreationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ItemIdElement
        {
            get
            {
                return _ItemIdElement;
            }
            set
            {
                OnItemIdElementChanging(value);
                ReportPropertyChanging("ItemIdElement");
                _ItemIdElement = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ItemIdElement");
                OnItemIdElementChanged();
            }
        }
        private global::System.Int64 _ItemIdElement;
        partial void OnItemIdElementChanging(global::System.Int64 value);
        partial void OnItemIdElementChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserIdUser
        {
            get
            {
                return _UserIdUser;
            }
            set
            {
                OnUserIdUserChanging(value);
                ReportPropertyChanging("UserIdUser");
                _UserIdUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserIdUser");
                OnUserIdUserChanged();
            }
        }
        private global::System.Int32 _UserIdUser;
        partial void OnUserIdUserChanging(global::System.Int32 value);
        partial void OnUserIdUserChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "ItemComment", "Item")]
        public VUItem Item
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VUItem>("Model.ItemComment", "Item").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VUItem>("Model.ItemComment", "Item").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<VUItem> ItemReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VUItem>("Model.ItemComment", "Item");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<VUItem>("Model.ItemComment", "Item", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "UserComment", "User")]
        public VUUser User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VUUser>("Model.UserComment", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VUUser>("Model.UserComment", "User").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<VUUser> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VUUser>("Model.UserComment", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<VUUser>("Model.UserComment", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="VUDroit")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VUDroit : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet VUDroit.
        /// </summary>
        /// <param name="idDroit">Valeur initiale de la propriété IdDroit.</param>
        /// <param name="admin">Valeur initiale de la propriété Admin.</param>
        public static VUDroit CreateVUDroit(global::System.Int32 idDroit, global::System.Boolean admin)
        {
            VUDroit vUDroit = new VUDroit();
            vUDroit.IdDroit = idDroit;
            vUDroit.Admin = admin;
            return vUDroit;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdDroit
        {
            get
            {
                return _IdDroit;
            }
            set
            {
                if (_IdDroit != value)
                {
                    OnIdDroitChanging(value);
                    ReportPropertyChanging("IdDroit");
                    _IdDroit = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdDroit");
                    OnIdDroitChanged();
                }
            }
        }
        private global::System.Int32 _IdDroit;
        partial void OnIdDroitChanging(global::System.Int32 value);
        partial void OnIdDroitChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Admin
        {
            get
            {
                return _Admin;
            }
            set
            {
                OnAdminChanging(value);
                ReportPropertyChanging("Admin");
                _Admin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Admin");
                OnAdminChanged();
            }
        }
        private global::System.Boolean _Admin;
        partial void OnAdminChanging(global::System.Boolean value);
        partial void OnAdminChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="VUDroitElement")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VUDroitElement : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet VUDroitElement.
        /// </summary>
        /// <param name="idVUDroitElement">Valeur initiale de la propriété IdVUDroitElement.</param>
        public static VUDroitElement CreateVUDroitElement(global::System.Int32 idVUDroitElement)
        {
            VUDroitElement vUDroitElement = new VUDroitElement();
            vUDroitElement.IdVUDroitElement = idVUDroitElement;
            return vUDroitElement;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdVUDroitElement
        {
            get
            {
                return _IdVUDroitElement;
            }
            set
            {
                if (_IdVUDroitElement != value)
                {
                    OnIdVUDroitElementChanging(value);
                    ReportPropertyChanging("IdVUDroitElement");
                    _IdVUDroitElement = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdVUDroitElement");
                    OnIdVUDroitElementChanged();
                }
            }
        }
        private global::System.Int32 _IdVUDroitElement;
        partial void OnIdVUDroitElementChanging(global::System.Int32 value);
        partial void OnIdVUDroitElementChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> EcrireUser
        {
            get
            {
                return _EcrireUser;
            }
            set
            {
                OnEcrireUserChanging(value);
                ReportPropertyChanging("EcrireUser");
                _EcrireUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EcrireUser");
                OnEcrireUserChanged();
            }
        }
        private Nullable<global::System.Boolean> _EcrireUser;
        partial void OnEcrireUserChanging(Nullable<global::System.Boolean> value);
        partial void OnEcrireUserChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> LireUser
        {
            get
            {
                return _LireUser;
            }
            set
            {
                OnLireUserChanging(value);
                ReportPropertyChanging("LireUser");
                _LireUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LireUser");
                OnLireUserChanged();
            }
        }
        private Nullable<global::System.Boolean> _LireUser;
        partial void OnLireUserChanging(Nullable<global::System.Boolean> value);
        partial void OnLireUserChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> EcrireGroupe
        {
            get
            {
                return _EcrireGroupe;
            }
            set
            {
                OnEcrireGroupeChanging(value);
                ReportPropertyChanging("EcrireGroupe");
                _EcrireGroupe = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EcrireGroupe");
                OnEcrireGroupeChanged();
            }
        }
        private Nullable<global::System.Boolean> _EcrireGroupe;
        partial void OnEcrireGroupeChanging(Nullable<global::System.Boolean> value);
        partial void OnEcrireGroupeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> LireGroupe
        {
            get
            {
                return _LireGroupe;
            }
            set
            {
                OnLireGroupeChanging(value);
                ReportPropertyChanging("LireGroupe");
                _LireGroupe = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LireGroupe");
                OnLireGroupeChanged();
            }
        }
        private Nullable<global::System.Boolean> _LireGroupe;
        partial void OnLireGroupeChanging(Nullable<global::System.Boolean> value);
        partial void OnLireGroupeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> EcrireAutre
        {
            get
            {
                return _EcrireAutre;
            }
            set
            {
                OnEcrireAutreChanging(value);
                ReportPropertyChanging("EcrireAutre");
                _EcrireAutre = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EcrireAutre");
                OnEcrireAutreChanged();
            }
        }
        private Nullable<global::System.Boolean> _EcrireAutre;
        partial void OnEcrireAutreChanging(Nullable<global::System.Boolean> value);
        partial void OnEcrireAutreChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> LireAutre
        {
            get
            {
                return _LireAutre;
            }
            set
            {
                OnLireAutreChanging(value);
                ReportPropertyChanging("LireAutre");
                _LireAutre = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LireAutre");
                OnLireAutreChanged();
            }
        }
        private Nullable<global::System.Boolean> _LireAutre;
        partial void OnLireAutreChanging(Nullable<global::System.Boolean> value);
        partial void OnLireAutreChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="VUElement")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(VUItem))]
    [KnownTypeAttribute(typeof(VUFolder))]
    public partial class VUElement : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet VUElement.
        /// </summary>
        /// <param name="idElement">Valeur initiale de la propriété IdElement.</param>
        /// <param name="nom">Valeur initiale de la propriété Nom.</param>
        /// <param name="dateCreation">Valeur initiale de la propriété DateCreation.</param>
        /// <param name="dateMAJ">Valeur initiale de la propriété DateMAJ.</param>
        /// <param name="userIdUser">Valeur initiale de la propriété UserIdUser.</param>
        /// <param name="vUDroitElementIdVUDroitElement">Valeur initiale de la propriété VUDroitElementIdVUDroitElement.</param>
        public static VUElement CreateVUElement(global::System.Int64 idElement, global::System.String nom, global::System.DateTime dateCreation, global::System.DateTime dateMAJ, global::System.Int32 userIdUser, global::System.Int32 vUDroitElementIdVUDroitElement)
        {
            VUElement vUElement = new VUElement();
            vUElement.IdElement = idElement;
            vUElement.Nom = nom;
            vUElement.DateCreation = dateCreation;
            vUElement.DateMAJ = dateMAJ;
            vUElement.UserIdUser = userIdUser;
            vUElement.VUDroitElementIdVUDroitElement = vUDroitElementIdVUDroitElement;
            return vUElement;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 IdElement
        {
            get
            {
                return _IdElement;
            }
            set
            {
                if (_IdElement != value)
                {
                    OnIdElementChanging(value);
                    ReportPropertyChanging("IdElement");
                    _IdElement = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdElement");
                    OnIdElementChanged();
                }
            }
        }
        private global::System.Int64 _IdElement;
        partial void OnIdElementChanging(global::System.Int64 value);
        partial void OnIdElementChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreation
        {
            get
            {
                return _DateCreation;
            }
            set
            {
                OnDateCreationChanging(value);
                ReportPropertyChanging("DateCreation");
                _DateCreation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreation");
                OnDateCreationChanged();
            }
        }
        private global::System.DateTime _DateCreation;
        partial void OnDateCreationChanging(global::System.DateTime value);
        partial void OnDateCreationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateMAJ
        {
            get
            {
                return _DateMAJ;
            }
            set
            {
                OnDateMAJChanging(value);
                ReportPropertyChanging("DateMAJ");
                _DateMAJ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateMAJ");
                OnDateMAJChanged();
            }
        }
        private global::System.DateTime _DateMAJ;
        partial void OnDateMAJChanging(global::System.DateTime value);
        partial void OnDateMAJChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserIdUser
        {
            get
            {
                return _UserIdUser;
            }
            set
            {
                OnUserIdUserChanging(value);
                ReportPropertyChanging("UserIdUser");
                _UserIdUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserIdUser");
                OnUserIdUserChanged();
            }
        }
        private global::System.Int32 _UserIdUser;
        partial void OnUserIdUserChanging(global::System.Int32 value);
        partial void OnUserIdUserChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> VUFolderIdElement
        {
            get
            {
                return _VUFolderIdElement;
            }
            set
            {
                OnVUFolderIdElementChanging(value);
                ReportPropertyChanging("VUFolderIdElement");
                _VUFolderIdElement = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VUFolderIdElement");
                OnVUFolderIdElementChanged();
            }
        }
        private Nullable<global::System.Int64> _VUFolderIdElement;
        partial void OnVUFolderIdElementChanging(Nullable<global::System.Int64> value);
        partial void OnVUFolderIdElementChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VUDroitElementIdVUDroitElement
        {
            get
            {
                return _VUDroitElementIdVUDroitElement;
            }
            set
            {
                OnVUDroitElementIdVUDroitElementChanging(value);
                ReportPropertyChanging("VUDroitElementIdVUDroitElement");
                _VUDroitElementIdVUDroitElement = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VUDroitElementIdVUDroitElement");
                OnVUDroitElementIdVUDroitElementChanged();
            }
        }
        private global::System.Int32 _VUDroitElementIdVUDroitElement;
        partial void OnVUDroitElementIdVUDroitElementChanging(global::System.Int32 value);
        partial void OnVUDroitElementIdVUDroitElementChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "UserFolder", "User")]
        public VUUser User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VUUser>("Model.UserFolder", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VUUser>("Model.UserFolder", "User").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<VUUser> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VUUser>("Model.UserFolder", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<VUUser>("Model.UserFolder", "User", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "VUDroitElementVUElement", "VUDroitElement")]
        public VUDroitElement VUDroitElement
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VUDroitElement>("Model.VUDroitElementVUElement", "VUDroitElement").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VUDroitElement>("Model.VUDroitElementVUElement", "VUDroitElement").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<VUDroitElement> VUDroitElementReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VUDroitElement>("Model.VUDroitElementVUElement", "VUDroitElement");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<VUDroitElement>("Model.VUDroitElementVUElement", "VUDroitElement", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="VUFolder")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VUFolder : VUElement
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet VUFolder.
        /// </summary>
        /// <param name="idElement">Valeur initiale de la propriété IdElement.</param>
        /// <param name="nom">Valeur initiale de la propriété Nom.</param>
        /// <param name="dateCreation">Valeur initiale de la propriété DateCreation.</param>
        /// <param name="dateMAJ">Valeur initiale de la propriété DateMAJ.</param>
        /// <param name="userIdUser">Valeur initiale de la propriété UserIdUser.</param>
        /// <param name="vUDroitElementIdVUDroitElement">Valeur initiale de la propriété VUDroitElementIdVUDroitElement.</param>
        public static VUFolder CreateVUFolder(global::System.Int64 idElement, global::System.String nom, global::System.DateTime dateCreation, global::System.DateTime dateMAJ, global::System.Int32 userIdUser, global::System.Int32 vUDroitElementIdVUDroitElement)
        {
            VUFolder vUFolder = new VUFolder();
            vUFolder.IdElement = idElement;
            vUFolder.Nom = nom;
            vUFolder.DateCreation = dateCreation;
            vUFolder.DateMAJ = dateMAJ;
            vUFolder.UserIdUser = userIdUser;
            vUFolder.VUDroitElementIdVUDroitElement = vUDroitElementIdVUDroitElement;
            return vUFolder;
        }

        #endregion
    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="VUGroupe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VUGroupe : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet VUGroupe.
        /// </summary>
        /// <param name="idGroupe">Valeur initiale de la propriété IdGroupe.</param>
        /// <param name="nom">Valeur initiale de la propriété Nom.</param>
        /// <param name="dateCreation">Valeur initiale de la propriété DateCreation.</param>
        /// <param name="dateMAJ">Valeur initiale de la propriété DateMAJ.</param>
        /// <param name="droitIdDroit">Valeur initiale de la propriété DroitIdDroit.</param>
        public static VUGroupe CreateVUGroupe(global::System.Int32 idGroupe, global::System.String nom, global::System.DateTime dateCreation, global::System.DateTime dateMAJ, global::System.Int32 droitIdDroit)
        {
            VUGroupe vUGroupe = new VUGroupe();
            vUGroupe.IdGroupe = idGroupe;
            vUGroupe.Nom = nom;
            vUGroupe.DateCreation = dateCreation;
            vUGroupe.DateMAJ = dateMAJ;
            vUGroupe.DroitIdDroit = droitIdDroit;
            return vUGroupe;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdGroupe
        {
            get
            {
                return _IdGroupe;
            }
            set
            {
                if (_IdGroupe != value)
                {
                    OnIdGroupeChanging(value);
                    ReportPropertyChanging("IdGroupe");
                    _IdGroupe = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdGroupe");
                    OnIdGroupeChanged();
                }
            }
        }
        private global::System.Int32 _IdGroupe;
        partial void OnIdGroupeChanging(global::System.Int32 value);
        partial void OnIdGroupeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreation
        {
            get
            {
                return _DateCreation;
            }
            set
            {
                OnDateCreationChanging(value);
                ReportPropertyChanging("DateCreation");
                _DateCreation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreation");
                OnDateCreationChanged();
            }
        }
        private global::System.DateTime _DateCreation;
        partial void OnDateCreationChanging(global::System.DateTime value);
        partial void OnDateCreationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateMAJ
        {
            get
            {
                return _DateMAJ;
            }
            set
            {
                OnDateMAJChanging(value);
                ReportPropertyChanging("DateMAJ");
                _DateMAJ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateMAJ");
                OnDateMAJChanged();
            }
        }
        private global::System.DateTime _DateMAJ;
        partial void OnDateMAJChanging(global::System.DateTime value);
        partial void OnDateMAJChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DroitIdDroit
        {
            get
            {
                return _DroitIdDroit;
            }
            set
            {
                OnDroitIdDroitChanging(value);
                ReportPropertyChanging("DroitIdDroit");
                _DroitIdDroit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DroitIdDroit");
                OnDroitIdDroitChanged();
            }
        }
        private global::System.Int32 _DroitIdDroit;
        partial void OnDroitIdDroitChanging(global::System.Int32 value);
        partial void OnDroitIdDroitChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "DroitGroupe", "Droit")]
        public VUDroit Droit
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VUDroit>("Model.DroitGroupe", "Droit").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VUDroit>("Model.DroitGroupe", "Droit").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<VUDroit> DroitReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VUDroit>("Model.DroitGroupe", "Droit");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<VUDroit>("Model.DroitGroupe", "Droit", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="VUItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VUItem : VUElement
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet VUItem.
        /// </summary>
        /// <param name="idElement">Valeur initiale de la propriété IdElement.</param>
        /// <param name="nom">Valeur initiale de la propriété Nom.</param>
        /// <param name="dateCreation">Valeur initiale de la propriété DateCreation.</param>
        /// <param name="dateMAJ">Valeur initiale de la propriété DateMAJ.</param>
        /// <param name="userIdUser">Valeur initiale de la propriété UserIdUser.</param>
        /// <param name="vUDroitElementIdVUDroitElement">Valeur initiale de la propriété VUDroitElementIdVUDroitElement.</param>
        /// <param name="type">Valeur initiale de la propriété Type.</param>
        public static VUItem CreateVUItem(global::System.Int64 idElement, global::System.String nom, global::System.DateTime dateCreation, global::System.DateTime dateMAJ, global::System.Int32 userIdUser, global::System.Int32 vUDroitElementIdVUDroitElement, global::System.String type)
        {
            VUItem vUItem = new VUItem();
            vUItem.IdElement = idElement;
            vUItem.Nom = nom;
            vUItem.DateCreation = dateCreation;
            vUItem.DateMAJ = dateMAJ;
            vUItem.UserIdUser = userIdUser;
            vUItem.VUDroitElementIdVUDroitElement = vUDroitElementIdVUDroitElement;
            vUItem.Type = type;
            return vUItem;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] FichierHD
        {
            get
            {
                return StructuralObject.GetValidValue(_FichierHD);
            }
            set
            {
                OnFichierHDChanging(value);
                ReportPropertyChanging("FichierHD");
                _FichierHD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FichierHD");
                OnFichierHDChanged();
            }
        }
        private global::System.Byte[] _FichierHD;
        partial void OnFichierHDChanging(global::System.Byte[] value);
        partial void OnFichierHDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UrlHD
        {
            get
            {
                return _UrlHD;
            }
            set
            {
                OnUrlHDChanging(value);
                ReportPropertyChanging("UrlHD");
                _UrlHD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UrlHD");
                OnUrlHDChanged();
            }
        }
        private global::System.String _UrlHD;
        partial void OnUrlHDChanging(global::System.String value);
        partial void OnUrlHDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UrlLD
        {
            get
            {
                return _UrlLD;
            }
            set
            {
                OnUrlLDChanging(value);
                ReportPropertyChanging("UrlLD");
                _UrlLD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UrlLD");
                OnUrlLDChanged();
            }
        }
        private global::System.String _UrlLD;
        partial void OnUrlLDChanging(global::System.String value);
        partial void OnUrlLDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] FichierLD
        {
            get
            {
                return StructuralObject.GetValidValue(_FichierLD);
            }
            set
            {
                OnFichierLDChanging(value);
                ReportPropertyChanging("FichierLD");
                _FichierLD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FichierLD");
                OnFichierLDChanged();
            }
        }
        private global::System.Byte[] _FichierLD;
        partial void OnFichierLDChanging(global::System.Byte[] value);
        partial void OnFichierLDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="VUUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VUUser : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet VUUser.
        /// </summary>
        /// <param name="idUser">Valeur initiale de la propriété IdUser.</param>
        /// <param name="nom">Valeur initiale de la propriété Nom.</param>
        /// <param name="prenom">Valeur initiale de la propriété Prenom.</param>
        /// <param name="login">Valeur initiale de la propriété Login.</param>
        /// <param name="password">Valeur initiale de la propriété Password.</param>
        /// <param name="dateCreation">Valeur initiale de la propriété DateCreation.</param>
        /// <param name="dateMAJ">Valeur initiale de la propriété DateMAJ.</param>
        /// <param name="groupeIdGroupe">Valeur initiale de la propriété GroupeIdGroupe.</param>
        public static VUUser CreateVUUser(global::System.Int32 idUser, global::System.String nom, global::System.String prenom, global::System.String login, global::System.String password, global::System.DateTime dateCreation, global::System.DateTime dateMAJ, global::System.Int32 groupeIdGroupe)
        {
            VUUser vUUser = new VUUser();
            vUUser.IdUser = idUser;
            vUUser.Nom = nom;
            vUUser.Prenom = prenom;
            vUUser.Login = login;
            vUUser.Password = password;
            vUUser.DateCreation = dateCreation;
            vUUser.DateMAJ = dateMAJ;
            vUUser.GroupeIdGroupe = groupeIdGroupe;
            return vUUser;
        }

        #endregion
        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUser
        {
            get
            {
                return _IdUser;
            }
            set
            {
                if (_IdUser != value)
                {
                    OnIdUserChanging(value);
                    ReportPropertyChanging("IdUser");
                    _IdUser = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdUser");
                    OnIdUserChanged();
                }
            }
        }
        private global::System.Int32 _IdUser;
        partial void OnIdUserChanging(global::System.Int32 value);
        partial void OnIdUserChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Prenom
        {
            get
            {
                return _Prenom;
            }
            set
            {
                OnPrenomChanging(value);
                ReportPropertyChanging("Prenom");
                _Prenom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Prenom");
                OnPrenomChanged();
            }
        }
        private global::System.String _Prenom;
        partial void OnPrenomChanging(global::System.String value);
        partial void OnPrenomChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreation
        {
            get
            {
                return _DateCreation;
            }
            set
            {
                OnDateCreationChanging(value);
                ReportPropertyChanging("DateCreation");
                _DateCreation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreation");
                OnDateCreationChanged();
            }
        }
        private global::System.DateTime _DateCreation;
        partial void OnDateCreationChanging(global::System.DateTime value);
        partial void OnDateCreationChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateMAJ
        {
            get
            {
                return _DateMAJ;
            }
            set
            {
                OnDateMAJChanging(value);
                ReportPropertyChanging("DateMAJ");
                _DateMAJ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateMAJ");
                OnDateMAJChanged();
            }
        }
        private global::System.DateTime _DateMAJ;
        partial void OnDateMAJChanging(global::System.DateTime value);
        partial void OnDateMAJChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupeIdGroupe
        {
            get
            {
                return _GroupeIdGroupe;
            }
            set
            {
                OnGroupeIdGroupeChanging(value);
                ReportPropertyChanging("GroupeIdGroupe");
                _GroupeIdGroupe = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GroupeIdGroupe");
                OnGroupeIdGroupeChanged();
            }
        }
        private global::System.Int32 _GroupeIdGroupe;
        partial void OnGroupeIdGroupeChanging(global::System.Int32 value);
        partial void OnGroupeIdGroupeChanged();

        #endregion
    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "GroupeUser", "Groupe")]
        public VUGroupe Groupe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VUGroupe>("Model.GroupeUser", "Groupe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VUGroupe>("Model.GroupeUser", "Groupe").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<VUGroupe> GroupeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<VUGroupe>("Model.GroupeUser", "Groupe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<VUGroupe>("Model.GroupeUser", "Groupe", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
